#define SECRET_SSID "PUT HERE THE SSID OF THE WIFI FROM THE FIRST LIGHT"

#define SECRET_PASS "PUT HERE THE PASSWORD OF THE WIFI FROM THE FIRST LIGHT"

#define SECRET_TOKEN_FROM_ONE "PUT HERE THE TOKEN OF THE FIRST LIGHT"

#define SECRET_TOKEN_FROM_TWO "PUT HERE THE TOKEN OF THE SECOND LIGHT"
